Update readme with complete instructions
luckyframework/heroku-buildpack-lucky pull request #4
Opened 2021-02-05 17:03 UTC by robacarp

2021-02-05 17:06 UTC, jwoertink commented on README.md
> +    0.36.1
This should probably link to something else. I can't imagine any of us remembering to come back and update this one bit each time a new crystal version drops 😂

2021-02-08 16:58 UTC, jwoertink requested changes

2021-02-08 16:58 UTC, jwoertink commented on README.md
> +  - sendgrid key: `heroku config:set SECRET_KEY_BASE=$(lucky gen.secret_key)`
```suggestion
  - secret key base: `heroku config:set SECRET_KEY_BASE=$(lucky gen.secret_key)`
```

2021-02-08 16:58 UTC, matthewmcgarvey approved these changes

2021-04-10 02:41 UTC, jwoertink approved these changes

2021-04-10 02:41 UTC, merged